@extends ('template')

@section ('content')

  <div class="Slider-View"> </div>
      
      <div class="About-logo">
        <img src="{{asset('assets/images/Logos/About-logo.jpg')}}" alt="">
      </div>

      <div class="About-content">
        <p>THE MOST FASHION FORWARD COLLEGE BRAND - FINALLY, TRENDY AND CUTE APPAREL FOR TAILGATES AND GAME DAYS IS HERE!</p>
        <p>THE STUDENTS BRAND</p>
        <p>HYPE & VICE ISN’T JUST A LOGO; IT’S A LIFESTYLE THAT REPRESENTS WHAT WE’RE DOING AND WHERE WE’RE HEADED. WE’RE ALWAYS PUSHING FORWARD: CHANNELING TODAY, PREPARING FOR TOMORROW. OUR VISION IS STRONG STATEMENTS ON SOFT FABRIC.</p>
        <p>H&V IS A BRAND THAT TAPS INTO THE COLLECTIVE SPIRIT OF YOUR COLLEGE EXPERIENCE. WE ARE MORE THAN JUST ANOTHER APPAREL LINE; WE ARE A STATEMENT MADE BY YOU, THE STUDENT. A STATEMENT THAT SAYS THAT YOU ARE DIFFERENT AND UNIQUE. WITH H&V YOU ARE PUSHING THE BANAL ASIDE AND ONLY SETTLING FOR THE EXTRAORDINARY.</p>
        <p>GO CASUAL, GO TRENDY... GO #HYPEANDVICE</p>
      </div>


@stop
